name: Build/release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build for (mac, win, linux)'
        required: true
        default: 'mac'
        type: choice
        options:
          - mac
          - win
          - linux

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.6.0'

      - name: Install dependencies
        run: npm ci

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platform: ${{ github.event.inputs.platform }}
          # Optional: Define the version number here if it's tagged
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/
        if: always()
