name: Build Electron App

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build for'
        required: true
        default: 'all'
        options:
          - all
          - mac
          - win
          - linux

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run build:${{ matrix.platform }}
        env:
          GH_TOKEN: dummy_token # Prevent GitHub publishing warnings

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.platform }}
          path: dist/
        if: always()
