name: Build Electron App

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.6.0

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Electron app
      - name: Build Electron App
        run: npm run build

      # Package the Electron app for the specific platform
      - name: Package Electron App
        run: npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }}
        env:
          NODE_ENV: production

      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ matrix.os }}
          path: dist/
