name: Build Video Dimmer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - macos
          - windows
          - linux

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: macos
            build_command: npm run build:mac
          - os: ubuntu-latest
            platform: linux
            build_command: npm run build:linux
          - os: windows-latest
            platform: windows
            build_command: npm run build:win
    if: >-
      github.event.inputs.platform == 'all' ||
      github.event.inputs.platform == matrix.platform ||
      github.event_name == 'push'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Update version and add author field (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          $packageJson = Get-Content package.json -Raw | ConvertFrom-Json
          $packageJson.version = $version
          Add-Member -InputObject $packageJson -NotePropertyName "author" -NotePropertyValue @{
            name = "Video Dimmer Team"
            email = "videodimmer@example.com"
          } -Force
          $packageJson | ConvertTo-Json -Depth 32 | Set-Content package.json

      - name: Update version and add author field (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          node -e 'const fs=require("fs"); const p=JSON.parse(fs.readFileSync("package.json")); p.version=process.env.VERSION; p.author={name:"Video Dimmer Team", email:"videodimmer@example.com"}; fs.writeFileSync("package.json", JSON.stringify(p, null, 2))'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.build_command }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.zip
          if-no-files-found: ignore
          retention-days: 5

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            **/*.exe
            **/*.dmg
            **/*.AppImage
            **/*.deb
            **/*.rpm
            **/*.zip
          generate_release_notes: true
